### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by probonopd** [antony-jr/blue-glow#1]
This is happens when I launch the application for the first time inside [Firejail](https://github.com/netblue30/firejail):

![](https://github.com/AppImage/appimage.github.io/blob/62efa4ce8d90715eb555ead574c46c8f6c0b258a/database/BlueGlow/screenshot.png?raw=true)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1605

**Comment by probonopd** [comment]
This is how we run AppImages inside Firejail:

https://github.com/AppImage/appimage.github.io/blob/4f9af729553b87d814a1b943d3ef8ef1aec5d7a1/code/worker.sh#L207-L225

**Comment by probonopd** [comment]
How is the `""` determined? By looking at the `$APPIMAGE` environment variable? Possibly it doesn't work this way (yet) when run inside Firejail. If so, we may want to request exporting `$APPIMAGE`, `$APPDIR`, and `$OWD` in the FIrejail project.

**Comment by antony-jr** [comment]
>  How is the "" determined? By looking at the $APPIMAGE environment variable? 

First we use the program arguments to determine the AppImage path(if the the program arguments contains an executable then it runs the updater and does not look inside the environmental variable) , if that fails then we go for **$APPIMAGE** environmental variable , if that also fails then we fail.

**Comment by probonopd** [comment]
Can you have a look at it running inside [Firejail](https://github.com/netblue30/firejail)? All AppImages must pass running a test inside Firejail in order to be listed on https://appimage.github.io/. Thanks.

```
firejail --quiet --noprofile --net=none --appimage ./Your.AppImage
```

**Comment by antony-jr** [comment]
I think the updater cannot get the AppImage path from the program arguments and the environmental variable. If firejail could just pass the original program arguments along with its working directory then the updater should work under firejail. It seems to be impossible to do a update inside a sandbox. Since the update modifies the file in the host system , The sandbox is preventing it. ( I don't think they would change this feature)

**Comment by antony-jr** [comment]
You should re-run this after the current build is finished and deployed.

**Comment by probonopd** [comment]
With the configuration I posted above, the application is not even allowed to access the network, so the intended behavior is that the application should say "Could not check for updates, please check your internet connectivity" or something like that.

If you run without `--net=none` then it can access the network and should be able to check whether a new version is available.

**Comment by probonopd** [comment]
Actually Firejail does export `$APPIMAGE`:

https://github.com/netblue30/firejail/blob/0d2f252230283ffcd97795b65e5f29ceaf9bf824/src/firejail/appimage.c#L129-L137

**Comment by antony-jr** [comment]
Then I think that the program argument should have pointed the executable itself and so the updater tries to update and show invalid AppImage since it is a normal ELF executable. I think I should change this behavior. Also I did try running it without ```--net=none``` which yields the same results.

**Comment by probonopd** [comment]
Maybe just change the order, first check for `$APPIMAGE` and only if that fails (it should never) look at `argv[0]`?

**Comment by antony-jr** [comment]
> Maybe just change the order, first check for $APPIMAGE and only if that fails (it should never) look at argv[0]?

Yes , that seems to fix it. The latest build should run under firejail.

**Comment by probonopd** [comment]
Thank you, it passed the test. 👍
