### ISSUE TITLE
[Enhancement]  New branding - New logo, banner and icons

### ISSUE THREAD

**Issue by atraest** [antony-jr/blue-glow#3]
Hello @antony-jr . Thanks for the nice work on this project and thanks for sharing!

The current icons don't work on dark backgrounds, so I decided to make new ones that does and also do new branding while at that.

I've made new icons that work on both light and dark backgrounds, a new logo for the project, new banner and a new smaller logo for the README.md.

- The bell icon is a modified version of the bell icon from the [Feather Icons](https://github.com/feathericons/feather) and it's under a [MIT License](https://opensource.org/licenses/MIT).
- The font used is [Source Serif Pro](https://fonts.google.com/specimen/Source+Serif+Pro) and it's under a [Open Font License](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web)

PR is ready for review. #2 

![Frame 4](https://user-images.githubusercontent.com/57003922/74879792-a76e5d00-5348-11ea-8e58-5ef6ed44431f.png)

![Frame 3](https://user-images.githubusercontent.com/57003922/74879806-af2e0180-5348-11ea-823c-3ffa556a82ff.png)

<p align="center">
    <img src="https://user-images.githubusercontent.com/57003922/74879880-dc7aaf80-5348-11ea-8991-5b1d1fb80dcd.png">
</p>

<p align="center">
    <img src="https://user-images.githubusercontent.com/57003922/74879891-e0a6cd00-5348-11ea-8835-95a255e5c33e.png">
</p>

<p align="center">
    <img src="https://user-images.githubusercontent.com/57003922/74879900-e43a5400-5348-11ea-9c63-7c80a8438129.png">
</p>

**Comment by antony-jr** [comment]
@cristianovitorino We look at it later, Thanks.

**Comment by antony-jr** [comment]
I completely rewrote the application with Material Design. Now you have Dark Mode, by default the application uses Light Mode. The settings can be changed once you authenticate your token. I hope you like the changes

**Comment by atraest** [comment]
> I completely rewrote the application with Material Design. Now you have Dark Mode, by default the application uses Light Mode. The settings can be changed once you authenticate your token. I hope you like the changes

Wow! It's beautiful! Material is very nice. I absolutely like the changes yes!

Do you want to make the tray icon follow the dark and light modes on code? If you're interested, I can rework the icon, make it more pronounceable and without the bubble and make the two versions, light and dark, so people with light or dark tray/bars can adjust the tray icon color by just tweaking the new dark/light mode/button you introduced on the UI.

**Comment by antony-jr** [comment]
The new application still has some bugs, some known are, the quit menu in system tray does not work. When you close the app with the **X** icon in the window title bar, the application closes unlike the older version which never had these issues. But I have no time. (But will fix it when I'm really bored of my day job)

**EDIT**: All known bugs are now fixed.

**I would gladly accept any artwork, but only do it if you have a lot of spare time.**

**Comment by atraest** [comment]
> The new application still has some bugs, some known are, the quit menu in system tray does not work. When you close the app with the **X** icon in the window title bar, the application closes unlike the older version which never had these issues. But I have no time. (But will fix it when I'm really bored of my day job)
> 
> **EDIT**: All known bugs are now fixed.
> 
> **I would gladly accept any artwork, but only do it if you have a lot of spare time.**

Oh sure, I love working on Open Source projects on my free time, no problem. As soon as I have the icon revision ready I'll post them here for you to review, if you approve it I'll do a PR soon after.

I'm unable do debug the "X" icon bug since I use the i3-gaps WM, no buttons anywhere haha, for me BlueGlow works and behaves normally.

**Comment by antony-jr** [comment]
Another thing to note is that, On each new release, if you use run on startup, Please save the settings disabling *Run On Startup* option and enable *Run On Startup* again and save.

Or else the old version will be launched on startup if you are using AppImage.

**Comment by atraest** [comment]
> Another thing to note is that, On each new release, if you use run on startup, Please save the settings disabling _Run On Startup_ option and enable _Run On Startup_ again and save.
> 
> Or else the old version will be launched on startup if you are using AppImage.

I see. Thanks for the heads up. Usually I delete the old `Appimage` and install and integrate the new one automatically with `AppimageLauncher` when `AppimageUpdate` doesn't work. And also, I don't use any Desktop Environment, all my startups are from the i3 config file or scripts that I write, makes no difference if I leave it on or off, for any application, it only matters if I login into a Desktop Environment like GNOME.

And thanks for doing Appimages consistently man, I apreciate that. I wish more devs would ship Appimages on Linux, or Flatpaks, so easy to install and manage and works on any distro.

**Comment by atraest** [comment]
Hey @antony-jr I've made the two dark and light icons.

Also I've me some revisions for the main logo, see what you think, if you like one of them or want to keep the current one.

I'll wait for your feedback to prepare a PR.

## NEW ICONS

**DARK ICON**
![icon-dark](https://user-images.githubusercontent.com/57003922/77213810-fbf12d80-6aea-11ea-8b84-56ea219dfe72.png)


**LIGHT ICON**
![icon-light-2](https://user-images.githubusercontent.com/57003922/77213813-fe538780-6aea-11ea-90f4-d6d2c5849cd4.png)

---

## **NEW LOGO REVISIONS**

**1 - NO LOGOTYPE JUST A LOGOMARK**
![Logo Proposal 1](https://user-images.githubusercontent.com/57003922/77213825-0a3f4980-6aeb-11ea-8d4d-4c2961288e28.png)

**2 - SIMPLE**
![Logo Proposal 2](https://user-images.githubusercontent.com/57003922/77213831-0f9c9400-6aeb-11ea-8b54-e9670228e179.png)

**3 - THE CURRENT LOGOTYPE, IMPROVED**
![Logo Proposal 3](https://user-images.githubusercontent.com/57003922/77213836-13301b00-6aeb-11ea-874e-e0c9c88b496d.png)

**4 - A NEW, DIFFERENT TAKE**
![Logo Proposal 4](https://user-images.githubusercontent.com/57003922/77213841-175c3880-6aeb-11ea-9b24-61ae0dcf2e16.png)

**Comment by antony-jr** [comment]
The simple design looks great.

**Comment by atraest** [comment]
> The simple design looks great.

Number 2 it is then : ) I'll do the final edit and prepare the PR soon.

**Comment by atraest** [comment]
Is this OK?

![mockup-2](https://user-images.githubusercontent.com/57003922/77227100-7c9c4200-6b5c-11ea-9d81-fa7793fa7f06.png)

**Comment by antony-jr** [comment]
I think we can use the same logo as given in no.1 for both dark and light modes. (i.e) The logo which is in blue color.

**Comment by atraest** [comment]
Good catch. This?

![mockup-2](https://user-images.githubusercontent.com/57003922/77227233-85414800-6b5d-11ea-8373-dae7e9fb9bc4.png)

**Comment by antony-jr** [comment]
Yep. Looks good. :+1:

**Comment by atraest** [comment]
PR is ready! #6
