### ISSUE TITLE
[Feature Request] Add support for notify-send

### ISSUE THREAD

**Issue by atraest** [antony-jr/blue-glow#4]
Hello. Would be nice to have [notify-send](https://ss64.com/bash/notify-send.html) to display the notification.

![quarta-19-fevereiro-2020_19-38-31](https://user-images.githubusercontent.com/57003922/74883310-75142e00-534f-11ea-96d3-961c4fdd2d66.png)

**Comment by antony-jr** [comment]
Added a option in the settings to use notify-send command if possible. Falls back to Qt's notification system if notify-send is not installed in your system.
