### ISSUE TITLE
Use Authorization Header instead of url param

### ISSUE THREAD

**Issue by ahmubashshir** [antony-jr/blue-glow#7]
GH api deprecated using access tokens in url parameter.

**Comment by antony-jr** [comment]
But it seems to work now. Anyways, I think we should move from deprecated api. I will update this on the next release.

**Comment by ahmubashshir** [comment]
I patched this :3

Here's the patch, <http://ix.io/3sRu>
	Mubashshir

**Comment by antony-jr** [comment]
@ahmubashshir Thanks. That seems good. But a PR would have been better but regardless. I can only patch it but the **build systems are a bit rusty so it will take a while for the binaries.**

**Comment by antony-jr** [comment]
@ahmubashshir I used your patch. But it seems you did not generate it with git format-patch so your contributions won't be shown in the git history. But I will add you as a contributor in the README.md

You can get the latest version of BlueGlow AppImage from releases with **development** tag.

**Comment by ahmubashshir** [comment]
ok :3
	Mubashshir
